# Generated by Django 5.2.4 on 2025-07-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandii', '0003_alter_orderdetail_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_cost',
            field=models.FloatField(default=0.0, help_text='Shipping cost in rupees'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_amount',
            field=models.FloatField(default=0.0, help_text='Total amount in rupees (product x quantity + shipping)'),
        ),
    ]
