# Generated by Django 5.2.4 on 2025-07-06 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandii', '0005_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='shipping_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
